#!/bin/bash
#task 3

pid_list=$(ls /proc | grep '^[0-9]*$')

for pid in $pid_list; do
  if [ -f "/proc/$pid/cmdline" ]; then
    process_name=$(tr '\0' ' ' < "/proc/$pid/cmdline")
    if [[ $process_name == *bash* ]]; then
      echo "PID: $pid, Process Name: $process_name"
    fi
  fi
done

