#!/usr/bin/env bash
# Task 3

for pid in /proc/[0-9]*; do
  if [ -f "$pid/cmdline" ]; then
    process_name=$(tr '\0' ' ' < "$pid/cmdline")
    if [[ $process_name == *bash* ]]; then
      pid=$(basename "$pid")
      echo "PID: $pid, Process Name: $process_name"
    fi
  fi
done
