#!/usr/bin/env bash
#Using awk to extract and format the IP and HTTP status code, then count occurrences
awk '{print $1, $9}' apache-access.log | sort | uniq -c | awk '{print $1, $2, $3}' | sort -rn

