#!/usr/bin/env bash
#superstitious numbers
i=1
while ((i<21)); do
	echo $i
	if ((i==4)); then
		echo "bad luck from china"
	elif ((i==9)); then
		echo "bad luck from Japan"
	elif ((i==17)); then
		echo "bad luck from Italy"
	fi
	((i++))
done
